In [7]:
import pandas as pd
from label_util import LabelingTool
import os

In [11]:
#читаем ваш датафрейс
df = pd.read_csv('data/vitya_flux_def.csv')
df = df.set_index('wordnet_id')
#760
#771
#824

In [12]:
df

,Unnamed: 0,subset,core_synset,core_lemma,hypernym_synsets,cohyponym_synsets,wikimedia_images,image_filename,definition,model_a,model_b
wordnet_id,,,,,,,,,,,
29148617,1595,predict_hypernym,genetic_disease.n.01,genetic_disease,['disease.n.01'],"['animal_disease.n.01', 'anthrax.n.02', 'asper...",['https://upload.wikimedia.org/wikipedia/commo...,A boy with Down syndrome using cordless drill ...,a disease or disorder that is inherited geneti...,black-forest-labs_FLUX.1-dev,Tencent-Hunyuan_HunyuanDiT-v1.2-Diffusers
2053030,1598,predict_hypernym,surpass.v.02,surpass,['beat.v.01'],"['cheat.v.02', 'checkmate.v.01', 'cream.v.02',...",['https://upload.wikimedia.org/wikipedia/commo...,Anabuki Surpass Joto at Osaka.jpg,be or do something to a greater degree,prompthero_openjourney,black-forest-labs_FLUX.1-dev
93221214,1603,predict_hypernym,plaything.n.01,plaything,['artifact.n.01'],"['americana.n.01', 'anachronism.n.02', 'antiqu...",['https://upload.wikimedia.org/wikipedia/commo...,Mexican guitars and toys.jpg,an artifact designed to be played with,runwayml_stable-diffusion-v1-5,black-forest-labs_FLUX.1-dev
3818090,1606,simple_triplet_2parent,neomycin.n.01,neomycin,"['antibiotic.n.01', 'antiseptic.n.01']","['actinomycin.n.01', 'amphotericin.n.01', 'ant...",['https://upload.wikimedia.org/wikipedia/commo...,Neomycin B C.svg,an antibiotic obtained from an actinomycete an...,black-forest-labs_FLUX.1-dev,playgroundai_playground-v2.5-1024px-aesthetic
4259202,1613,simple_triplet_2parent,solenoid.n.01,solenoid,"['coil.n.06', 'magnet.n.01']","['armature.n.01', 'astatic_coils.n.01', 'choke...",['https://upload.wikimedia.org/wikipedia/commo...,Solenoid-1.png,a coil of wire around an iron core; becomes a ...,black-forest-labs_FLUX.1-dev,stabilityai_sdxl-turbo
...,...,...,...,...,...,...,...,...,...,...,...
61635816,2431,predict_hypernym_llama,spirit.n.04,spirit,['spiritual_being.n.01'],"['angel.n.01', 'deity.n.01', 'eon.n.03', 'fair...",['https://upload.wikimedia.org/wikipedia/commo...,B-2 Spirit original.jpg,a nonphysical part of a person which is the se...,stabilityai_stable-diffusion-3-medium-diffusers,black-forest-labs_FLUX.1-dev
18845198,2432,predict_hypernym_llama,adult.n.01,celebrity,['person.n.01'],"['abator.n.01', 'abjurer.n.01', 'abomination.n...",['https://upload.wikimedia.org/wikipedia/commo...,Celebrity Summit-DSC 0134w.jpg,Celebrity refers to a person who is widely rec...,playgroundai_playground-v2.5-1024px-aesthetic,black-forest-labs_FLUX.1-dev
69489691,2434,leafs_and_no_leafs_llama,white.n.01,albino,['person.n.01'],"['abator.n.01', 'abjurer.n.01', 'abomination.n...",['https://upload.wikimedia.org/wikipedia/commo...,Albino Alligator 2008.jpg,a person or animal lacking pigment in their sk...,black-forest-labs_FLUX.1-dev,retrieval
91790573,2468,predict_hypernym_llama,professional.n.01,lawyer,['adult.n.01'],"['brachycephalic.n.01', 'caregiver.n.02', 'cat...",['https://upload.wikimedia.org/wikipedia/commo...,Diana Ellis - 19 Oct 2011.jpg,"A professional authorized to practice law, who...",retrieval,black-forest-labs_FLUX.1-dev
91980352,2469,predict_hypernym_llama,modality.n.03,sensation,['sense.n.03'],['sensitivity.n.01'],['https://upload.wikimedia.org/wikipedia/commo...,"Allium purple sensation, 17-04-2024 (d.j.b.) 0...",a physical feeling or perception resulting fro...,stabilityai_stable-diffusion-xl-base-1.0,black-forest-labs_FLUX.1-dev

In [13]:
#df = df.drop(columns=['assessor_vitya'])

In [14]:
labeler = LabelingTool(
    dataset=df,
    assessor_id='vitya', # ваше имя 
    image_path='/home/data/v.moskvoretskii/cache/taxo_demo_images/images', #путь до разархивированных картинок
    save2path='vitya_nodef_flux.csv', # куда сохранится
    img_type='.png', # не нужно, внутри пофикшено все
    ignore_all_labeled=True
    )

All samples are labeled!

In [15]:
labeler.label_samples()

VBox(children=(HBox(children=(Output(), Output()), layout=Layout(align_items='center')), VBox(children=(Output…

In [7]:
df

,Unnamed: 0,subset,core_synset,core_lemma,hypernym_synsets,cohyponym_synsets,wikimedia_images,image_filename,definition,model_a,model_b,assessor_vitya
wordnet_id,,,,,,,,,,,,
5410315,1684,predict_hypernym,gonadotropin.n.01,gonadotropin,['hormone.n.01'],"['adrenocorticotropic_hormone.n.01', 'adrenost...",['https://upload.wikimedia.org/wikipedia/commo...,Estrogen provocation test and gonadotropin sur...,hormone secreted by the anterior pituitary gla...,prompthero_openjourney,stabilityai_stable-diffusion-3-medium-diffusers,3.0
33877584,1685,appendix_llama,coinage.n.01,numismatics,['currency.n.01'],"['cash.n.01', 'eurocurrency.n.01', 'hard_curre...",['https://upload.wikimedia.org/wikipedia/commo...,Coin collectors and enthusiasts by Yogabrata C...,"The study and collection of coins, paper curre...",prompthero_openjourney,stabilityai_sdxl-turbo,1.0
56250900,1686,appendix_llama,coin.n.01,bee,['coinage.n.01'],[],['https://upload.wikimedia.org/wikipedia/commo...,Bee Collecting Pollen 2004-08-14.jpg,a flying insect known for its role in pollinat...,PixArt-alpha_PixArt-Sigma-XL-2-512-MS,DeepFloyd_IF-I-XL-v1.0,2.0
70890935,1687,appendix_llama,coin.n.01,gold coin,['coinage.n.01'],[],['https://upload.wikimedia.org/wikipedia/commo...,"Gold coin of the Kushan empire, king Vasudeva ...",A gold coin is a piece of bullion or refined m...,PixArt-alpha_PixArt-Sigma-XL-2-512-MS,retrieval,1.0
66203715,1688,appendix_llama,coin.n.01,transformation,['coinage.n.01'],[],['https://upload.wikimedia.org/wikipedia/commo...,Bacterial Transformation.svg,A profound or radical change in something from...,stabilityai_stable-diffusion-xl-base-1.0,playgroundai_playground-v2.5-1024px-aesthetic,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...
92219553,2521,predict_hypernym_llama,activity.n.01,self-worship,['act.n.02'],"['acquiring.n.01', 'action.n.01', 'assumption....",['https://upload.wikimedia.org/wikipedia/commo...,2016 Bahai House of Worship Langenhain 1 ks01.jpg,An excessive and exaggerated esteem or admirat...,stabilityai_stable-diffusion-xl-base-1.0,prompthero_openjourney,0.0
65034633,2522,predict_hypernym_llama,adult.n.01,oldster,['person.n.01'],"['abator.n.01', 'abjurer.n.01', 'abomination.n...",['https://upload.wikimedia.org/wikipedia/commo...,Старик (oldster) (50904206177).jpg,"a term used to describe an older person, often...",stabilityai_stable-diffusion-xl-base-1.0,runwayml_stable-diffusion-v1-5,0.0
25851699,2523,predict_hypernym_llama,deck.n.01,deck,['platform.n.01'],"['auction_block.n.01', 'bandstand.n.01', 'catw...",['https://upload.wikimedia.org/wikipedia/commo...,Bridge and deck of Gullbritt.jpg,a platform extending horizontally from one sid...,stabilityai_stable-diffusion-3-medium-diffusers,kandinsky-community_kandinsky-3,1.0
85363317,2524,simple_triplet_2parent_llama,man-made_fiber.n.01,nylon,['fiber.n.01'],"['bassine.n.01', 'bristle.n.01', 'byssus.n.01'...",['https://upload.wikimedia.org/wikipedia/commo...,Черные чулки.jpg,"A synthetic polymer, typically made from petro...",DeepFloyd_IF-I-XL-v1.0,PixArt-alpha_PixArt-Sigma-XL-2-512-MS,1.0
41772405,2525,predict_hypernym_llama,form.n.08,questionnaire,['document.n.01'],"['ballot.n.01', 'brevet.n.01', 'capitulation.n...",['https://upload.wikimedia.org/wikipedia/commo...,Questionnaire-checklist-completed.png,A set of printed or written questions used for...,stabilityai_stable-diffusion-xl-base-1.0,Tencent-Hunyuan_HunyuanDiT-v1.2-Diffusers,0.0

In [8]:
len(df.index[df['assessor_vitya'].notna()])

842

In [ ]:
output = pd.read_csv('test_output.csv', index_col=0) # проверяем что все ок

In [9]:
df1 = pd.read_csv('vitya_def.csv')

In [10]:
df1

,wordnet_id,Unnamed: 0,subset,core_synset,core_lemma,hypernym_synsets,cohyponym_synsets,wikimedia_images,image_filename,definition,model_a,model_b,assessor_vitya
0,5410315,1684,predict_hypernym,gonadotropin.n.01,gonadotropin,['hormone.n.01'],"['adrenocorticotropic_hormone.n.01', 'adrenost...",['https://upload.wikimedia.org/wikipedia/commo...,Estrogen provocation test and gonadotropin sur...,hormone secreted by the anterior pituitary gla...,prompthero_openjourney,stabilityai_stable-diffusion-3-medium-diffusers,3.0
1,33877584,1685,appendix_llama,coinage.n.01,numismatics,['currency.n.01'],"['cash.n.01', 'eurocurrency.n.01', 'hard_curre...",['https://upload.wikimedia.org/wikipedia/commo...,Coin collectors and enthusiasts by Yogabrata C...,"The study and collection of coins, paper curre...",prompthero_openjourney,stabilityai_sdxl-turbo,1.0
2,56250900,1686,appendix_llama,coin.n.01,bee,['coinage.n.01'],[],['https://upload.wikimedia.org/wikipedia/commo...,Bee Collecting Pollen 2004-08-14.jpg,a flying insect known for its role in pollinat...,PixArt-alpha_PixArt-Sigma-XL-2-512-MS,DeepFloyd_IF-I-XL-v1.0,2.0
3,70890935,1687,appendix_llama,coin.n.01,gold coin,['coinage.n.01'],[],['https://upload.wikimedia.org/wikipedia/commo...,"Gold coin of the Kushan empire, king Vasudeva ...",A gold coin is a piece of bullion or refined m...,PixArt-alpha_PixArt-Sigma-XL-2-512-MS,retrieval,1.0
4,66203715,1688,appendix_llama,coin.n.01,transformation,['coinage.n.01'],[],['https://upload.wikimedia.org/wikipedia/commo...,Bacterial Transformation.svg,A profound or radical change in something from...,stabilityai_stable-diffusion-xl-base-1.0,playgroundai_playground-v2.5-1024px-aesthetic,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
837,92219553,2521,predict_hypernym_llama,activity.n.01,self-worship,['act.n.02'],"['acquiring.n.01', 'action.n.01', 'assumption....",['https://upload.wikimedia.org/wikipedia/commo...,2016 Bahai House of Worship Langenhain 1 ks01.jpg,An excessive and exaggerated esteem or admirat...,stabilityai_stable-diffusion-xl-base-1.0,prompthero_openjourney,0.0
838,65034633,2522,predict_hypernym_llama,adult.n.01,oldster,['person.n.01'],"['abator.n.01', 'abjurer.n.01', 'abomination.n...",['https://upload.wikimedia.org/wikipedia/commo...,Старик (oldster) (50904206177).jpg,"a term used to describe an older person, often...",stabilityai_stable-diffusion-xl-base-1.0,runwayml_stable-diffusion-v1-5,0.0
839,25851699,2523,predict_hypernym_llama,deck.n.01,deck,['platform.n.01'],"['auction_block.n.01', 'bandstand.n.01', 'catw...",['https://upload.wikimedia.org/wikipedia/commo...,Bridge and deck of Gullbritt.jpg,a platform extending horizontally from one sid...,stabilityai_stable-diffusion-3-medium-diffusers,kandinsky-community_kandinsky-3,1.0
840,85363317,2524,simple_triplet_2parent_llama,man-made_fiber.n.01,nylon,['fiber.n.01'],"['bassine.n.01', 'bristle.n.01', 'byssus.n.01'...",['https://upload.wikimedia.org/wikipedia/commo...,Черные чулки.jpg,"A synthetic polymer, typically made from petro...",DeepFloyd_IF-I-XL-v1.0,PixArt-alpha_PixArt-Sigma-XL-2-512-MS,1.0
841,41772405,2525,predict_hypernym_llama,form.n.08,questionnaire,['document.n.01'],"['ballot.n.01', 'brevet.n.01', 'capitulation.n...",['https://upload.wikimedia.org/wikipedia/commo...,Questionnaire-checklist-completed.png,A set of printed or written questions used for...,stabilityai_stable-diffusion-xl-base-1.0,Tencent-Hunyuan_HunyuanDiT-v1.2-Diffusers,0.0