In [1]:
import pandas as pd
import random
import os
import nltk
nltk.download('wordnet')
from nltk.corpus import wordnet as wn
from tqdm import tqdm

[nltk_data] Downloading package wordnet to /root/nltk_data...

In [4]:
human_def = pd.read_csv('/home/data/v.moskvoretskii/TaxoGen/data/labeling/human_with_flux_def_final.csv')
human_def = human_def.drop(columns=['Unnamed: 0'])
human_def = human_def.sort_values(by=['wordnet_id'])

human_nodef = pd.read_csv('/home/data/v.moskvoretskii/TaxoGen/data/labeling/human_with_flux_nodef_final.csv')
human_nodef = human_nodef.sort_values(by=['wordnet_id'])


gpt_def = pd.read_csv('/home/data/v.moskvoretskii/TaxoGen/data/main_gpt4_def_with_flux.csv')
gpt_nodef = pd.read_csv('/home/data/v.moskvoretskii/TaxoGen/data/main_gpt4_nodef_with_flux.csv')

In [78]:
def add_id(df):

    df['id'] = (df['wordnet_id'].astype(str) + df['model_a'] + df['model_b']).apply(hash)
    return df

human_def = add_id(human_def)
human_nodef = add_id(human_nodef)
gpt_def = add_id(gpt_def)
gpt_nodef = add_id(gpt_nodef)

In [83]:
print(len(human_def), len(human_nodef))
final = human_def.merge(human_nodef[['result', 'id']], on='id', suffixes=('_human_def', '_human_nodef'))
print(len(final))

3983 3983
3983

In [84]:
gpt_final = gpt_nodef.merge(gpt_def[['result', 'id']], on='id', suffixes=('_gpt_nodef', '_gpt_def'), how='left')

In [85]:
final2 = final.merge(gpt_final[['id', 'result_gpt_nodef', 'result_gpt_def']], on='id')

In [86]:
final2[final2.duplicated(subset=['id'])]

Empty DataFrame
Columns: [wordnet_id, subset, core_synset, core_lemma, hypernym_synsets, cohyponym_synsets, wikimedia_images, image_filename, definition, model_a, model_b, result_human_def, id, result_human_nodef, result_gpt_nodef, result_gpt_def]
Index: []

In [88]:
final2.to_csv('data/final_final_final.csv', index=False)

In [29]:
((human_def.sort_values(by=['wordnet_id'])['model_a']).values != (gpt_def.sort_values(by=['wordnet_id'])['model_a']).values).sum()

608

In [24]:
(gpt_def.sort_values(by=['wordnet_id'])['wordnet_id'])

616         2684
664         3431
2637       81127
1722      103793
2427      105194
          ...
525     99862294
2589    99888646
977     99908103
2611    99915098
1343    99946324
Name: wordnet_id, Length: 3983, dtype: int64

In [5]:
df = pd.read_csv('data/main_for_flux.csv', index_col=0)

In [6]:
df

,Unnamed: 0,subset,wordnet_id,core_synset,core_lemma,hypernym_synsets,cohyponym_synsets,wikimedia_images,image_filename,definition,model_a,model_b
16,16,appendix,13392688,guinea.n.01,guinea,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,Guinea (orthographic projection).svg,a former British gold coin worth 21 shillings,black-forest-labs_FLUX.1-dev,stabilityai_sdxl-turbo
17,17,appendix,13389949,half_crown.n.01,half_crown,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,Coins (Nz Half Crowns 1933 To 1966 Set In Fold...,an English coin worth half a crown,Tencent-Hunyuan_HunyuanDiT-v1.2-Diffusers,black-forest-labs_FLUX.1-dev
18,18,appendix,13390405,half_dollar.n.01,half_dollar,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,Back of 50 cent coin.jpg,a United States coin worth half of a dollar,black-forest-labs_FLUX.1-dev,Tencent-Hunyuan_HunyuanDiT-v1.2-Diffusers
24,24,appendix,13390139,nickel.n.02,nickel,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,Nickel electrolytic and 1cm3 cube.jpg,a United States coin worth one twentieth of a ...,PixArt-alpha_PixArt-Sigma-XL-2-512-MS,black-forest-labs_FLUX.1-dev
38,38,appendix,4959672,chromatic_color.n.01,chromatic,['color.n.01'],"['achromatic_color.n.01', 'chromatic_color.n.0...",['https://upload.wikimedia.org/wikipedia/commo...,Rothenberg propriety diatonic scale chromatic ...,a color that has hue,stabilityai_stable-diffusion-xl-base-1.0,black-forest-labs_FLUX.1-dev
...,...,...,...,...,...,...,...,...,...,...,...,...
3342,3342,predict_hypernym_llama,27106238,leave.v.01,run,[],[],['https://upload.wikimedia.org/wikipedia/commo...,WeesenerBach.JPG,a continuous period of performing a certain ac...,black-forest-labs_FLUX.1-dev,stabilityai_stable-diffusion-3-medium-diffusers
3348,3348,predict_hypernym_llama,10080493,autoloader.n.01,pistol,['firearm.n.01'],"['muzzle_loader.n.01', 'pistol.n.01', 'repeati...",['https://upload.wikimedia.org/wikipedia/commo...,M9-pistolet.jpg,A handheld firearm designed to be operated wit...,stabilityai_sdxl-turbo,black-forest-labs_FLUX.1-dev
3350,3350,simple_triplet_2parent_llama,53572397,nitrogen.n.01,liquid nitrogen,"['chemical_element.n.01', 'gas.n.02']","['actinium.n.01', 'allotrope.n.01', 'argon.n.0...",['https://upload.wikimedia.org/wikipedia/commo...,Fluessiger Stickstoff.jpg,"a colorless, odorless, extremely cold liquid u...",black-forest-labs_FLUX.1-dev,DeepFloyd_IF-I-XL-v1.0
3358,3358,predict_hypernym_llama,18190594,asian.n.01,turk,"['inhabitant.n.01', 'person_of_color.n.01']","['alsatian.n.01', 'american.n.01', 'american.n...",['https://upload.wikimedia.org/wikipedia/commo...,Grand Turk and Salt Cay Islands.jpg,"a native or inhabitant of Turkey, or a person ...",black-forest-labs_FLUX.1-dev,PixArt-alpha_PixArt-Sigma-XL-2-512-MS
3368,3368,predict_hypernym_llama,13967420,body_part.n.01,abdomen,['part.n.03'],"['acicula.n.01', 'base.n.04', 'corner.n.09', '...",['https://upload.wikimedia.org/wikipedia/commo...,Abdomen-periumbilical region.png,A part of the body that lies between the thora...,retrieval,black-forest-labs_FLUX.1-dev

In [2]:
models_list = os.listdir('/home/data/v.moskvoretskii/taxo_demo_images/images/')

In [3]:
models_list

['stabilityai_sdxl-turbo',
 'retrieval',
 'runwayml_stable-diffusion-v1-5',
 'Tencent-Hunyuan_HunyuanDiT-v1.2-Diffusers',
 'playgroundai_playground-v2.5-1024px-aesthetic',
 'prompthero_openjourney',
 'kandinsky-community_kandinsky-3',
 'stabilityai_stable-diffusion-xl-base-1.0',
 'PixArt-alpha_PixArt-Sigma-XL-2-512-MS',
 'DeepFloyd_IF-I-XL-v1.0',
 'stabilityai_stable-diffusion-3-medium-diffusers']

In [34]:
wn.synsets('coin')[0].lemmas()

[Lemma('coin.n.01.coin')]

In [32]:
for synset in wn.synsets('coin')[0].hyponyms():
    print(synset.hyponyms())

[]
[]
[]
[]
[Synset('silver_dollar.n.01'), Synset('susan_b_anthony_dollar.n.01')]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[Synset('new_penny.n.01'), Synset('copper.n.02')]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]

In [33]:
wn.synset_from_pos_and_offset('n', 56250900)

/usr/local/lib/python3.10/dist-packages/nltk/corpus/reader/wordnet.py:1580: UserWarning: No WordNet synset found for pos=n at offset=56250900.
  warnings.warn(f"No WordNet synset found for pos={pos} at offset={offset}.")

In [44]:
df['definition'] = [wn.synset(df['core_synset'][i]).definition() for i in tqdm(range(len(df)))]

100%|██████████| 3370/3370 [00:00<00:00, 99129.00it/s]

In [45]:
df

,subset,wordnet_id,core_synset,core_lemma,hypernym_synsets,cohyponym_synsets,wikimedia_images,image_filename,definition
0,appendix,13388245,coin.n.01,coin,['coinage.n.01'],['coin.n.01'],['https://upload.wikimedia.org/wikipedia/commo...,"India, Kushan, Vasudeva II, 3rd century - Coin...",a flat metal piece (usually a disc) used as money
1,appendix,13389105,bawbee.n.01,bawbee,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,Mary bawbee 1542 127326.jpg,an old Scottish coin of little value
2,appendix,13389194,bezant.n.01,bezant,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,Crusader coins of the Kingdom of Jerusalem.jpg,a gold coin of the Byzantine Empire; widely ci...
3,appendix,13388111,change.n.08,change,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,Change in Average Temperature With Fahrenheit.svg,coins of small denomination regarded collectively
4,appendix,13389864,crown.n.06,crown,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,서봉총 금관 금제드리개.jpg,an English coin worth 5 shillings
...,...,...,...,...,...,...,...,...,...
3365,leafs_and_no_leafs_llama,41796839,area.n.03,renal area,['body_part.n.01'],"['abdomen.n.01', 'adnexa.n.01', 'ambulacrum.n....",['https://upload.wikimedia.org/wikipedia/commo...,CT of sclerotic lesions in the skull in renal ...,a part of an animal that has a special functio...
3366,predict_hypernym_llama,36389327,card_player.n.01,bridge player,['player.n.01'],"['ballplayer.n.01', 'billiard_player.n.01', 'b...",['https://upload.wikimedia.org/wikipedia/commo...,Kevin Collins (bridge player).jpg,someone who plays (or knows how to play) card ...
3367,predict_hypernym_llama,27347584,domestic_partner.n.01,married woman,['person.n.01'],"['abator.n.01', 'abjurer.n.01', 'abomination.n...",['https://upload.wikimedia.org/wikipedia/commo...,The Woman He Married (1922) - 4.jpg,a person (not necessarily a spouse) with whom ...
3368,predict_hypernym_llama,13967420,body_part.n.01,abdomen,['part.n.03'],"['acicula.n.01', 'base.n.04', 'corner.n.09', '...",['https://upload.wikimedia.org/wikipedia/commo...,Abdomen-periumbilical region.png,any part of an organism such as an organ or ex...
3369,predict_hypernym_llama,78890307,hormone.n.01,gonadotropin,['secretion.n.02'],"['autacoid.n.01', 'ganoin.n.01', 'intestinal_j...",['https://upload.wikimedia.org/wikipedia/commo...,Estrogen provocation test and gonadotropin sur...,the secretion of an endocrine gland that is tr...

In [46]:

# target_size = 4 * 1000
# rows_needed = target_size - len(df)
# additional_rows = df.sample(n=rows_needed, replace=True)
# expanded_df = pd.concat([df, additional_rows], ignore_index=True)

#models_list = ['SD3', 'SDXL', 'SDXL_Turbo', 'Kandinsky', 'PixArt_Sigma', 'Playground', 'IF', 'Openjourney', 'Hunyuan-DiT', 'SD_V1.5', 'Retrieved']

def sample_model_pair(models_list):
    return random.sample(models_list, 2)

# Adding the sampled pairs to the dataframe
df[['model_a', 'model_b']] = df.apply(lambda row: pd.Series(sample_model_pair(models_list)), axis=1)

In [47]:
df

,subset,wordnet_id,core_synset,core_lemma,hypernym_synsets,cohyponym_synsets,wikimedia_images,image_filename,definition,model_a,model_b
0,appendix,13388245,coin.n.01,coin,['coinage.n.01'],['coin.n.01'],['https://upload.wikimedia.org/wikipedia/commo...,"India, Kushan, Vasudeva II, 3rd century - Coin...",a flat metal piece (usually a disc) used as money,playgroundai_playground-v2.5-1024px-aesthetic,retrieval
1,appendix,13389105,bawbee.n.01,bawbee,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,Mary bawbee 1542 127326.jpg,an old Scottish coin of little value,runwayml_stable-diffusion-v1-5,stabilityai_stable-diffusion-xl-base-1.0
2,appendix,13389194,bezant.n.01,bezant,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,Crusader coins of the Kingdom of Jerusalem.jpg,a gold coin of the Byzantine Empire; widely ci...,PixArt-alpha_PixArt-Sigma-XL-2-512-MS,runwayml_stable-diffusion-v1-5
3,appendix,13388111,change.n.08,change,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,Change in Average Temperature With Fahrenheit.svg,coins of small denomination regarded collectively,DeepFloyd_IF-I-XL-v1.0,kandinsky-community_kandinsky-3
4,appendix,13389864,crown.n.06,crown,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,서봉총 금관 금제드리개.jpg,an English coin worth 5 shillings,retrieval,DeepFloyd_IF-I-XL-v1.0
...,...,...,...,...,...,...,...,...,...,...,...
3365,leafs_and_no_leafs_llama,41796839,area.n.03,renal area,['body_part.n.01'],"['abdomen.n.01', 'adnexa.n.01', 'ambulacrum.n....",['https://upload.wikimedia.org/wikipedia/commo...,CT of sclerotic lesions in the skull in renal ...,a part of an animal that has a special functio...,retrieval,stabilityai_stable-diffusion-xl-base-1.0
3366,predict_hypernym_llama,36389327,card_player.n.01,bridge player,['player.n.01'],"['ballplayer.n.01', 'billiard_player.n.01', 'b...",['https://upload.wikimedia.org/wikipedia/commo...,Kevin Collins (bridge player).jpg,someone who plays (or knows how to play) card ...,playgroundai_playground-v2.5-1024px-aesthetic,runwayml_stable-diffusion-v1-5
3367,predict_hypernym_llama,27347584,domestic_partner.n.01,married woman,['person.n.01'],"['abator.n.01', 'abjurer.n.01', 'abomination.n...",['https://upload.wikimedia.org/wikipedia/commo...,The Woman He Married (1922) - 4.jpg,a person (not necessarily a spouse) with whom ...,kandinsky-community_kandinsky-3,stabilityai_sdxl-turbo
3368,predict_hypernym_llama,13967420,body_part.n.01,abdomen,['part.n.03'],"['acicula.n.01', 'base.n.04', 'corner.n.09', '...",['https://upload.wikimedia.org/wikipedia/commo...,Abdomen-periumbilical region.png,any part of an organism such as an organ or ex...,playgroundai_playground-v2.5-1024px-aesthetic,runwayml_stable-diffusion-v1-5
3369,predict_hypernym_llama,78890307,hormone.n.01,gonadotropin,['secretion.n.02'],"['autacoid.n.01', 'ganoin.n.01', 'intestinal_j...",['https://upload.wikimedia.org/wikipedia/commo...,Estrogen provocation test and gonadotropin sur...,the secretion of an endocrine gland that is tr...,runwayml_stable-diffusion-v1-5,playgroundai_playground-v2.5-1024px-aesthetic

In [48]:
df.to_csv('main.csv', index=0)

In [7]:
n = len(df) // 4

# Splitting into four parts
df1 = df.iloc[:n]
df2 = df.iloc[n:2*n]
df3 = df.iloc[2*n:3*n]
df4 = df.iloc[3*n:]

In [8]:
len(df1), len(df4)

(153, 154)

In [9]:
df1.to_csv('data/alina_flux_def.csv', index=0)
df2.to_csv('data/kate_flux_def.csv', index=0)
df3.to_csv('data/vitya_flux_def.csv', index=0)
df4.to_csv('data/ira_flux_def.csv', index=0)

In [38]:
df3.loc[1784]

subset                                                  appendix_llama
wordnet_id                                                    10077077
core_synset                                             furniture.n.01
core_lemma                                                bird of prey
hypernym_synsets                                   ['furnishing.n.02']
cohyponym_synsets     ['appointment.n.03', 'curtain.n.01', 'rug.n.01']
wikimedia_images     ['https://upload.wikimedia.org/wikipedia/commo...
image_filename                    Bald.eagle.closeup.arp-sh.750pix.jpg
Name: 1784, dtype: object

In [2]:
df = pd.read_csv('main.csv')
df

,subset,wordnet_id,core_synset,core_lemma,hypernym_synsets,cohyponym_synsets,wikimedia_images,image_filename,definition,model_a,model_b
0,appendix,13388245,coin.n.01,coin,['coinage.n.01'],['coin.n.01'],['https://upload.wikimedia.org/wikipedia/commo...,"India, Kushan, Vasudeva II, 3rd century - Coin...",a flat metal piece (usually a disc) used as money,playgroundai_playground-v2.5-1024px-aesthetic,retrieval
1,appendix,13389105,bawbee.n.01,bawbee,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,Mary bawbee 1542 127326.jpg,an old Scottish coin of little value,runwayml_stable-diffusion-v1-5,stabilityai_stable-diffusion-xl-base-1.0
2,appendix,13389194,bezant.n.01,bezant,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,Crusader coins of the Kingdom of Jerusalem.jpg,a gold coin of the Byzantine Empire; widely ci...,PixArt-alpha_PixArt-Sigma-XL-2-512-MS,runwayml_stable-diffusion-v1-5
3,appendix,13388111,change.n.08,change,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,Change in Average Temperature With Fahrenheit.svg,coins of small denomination regarded collectively,DeepFloyd_IF-I-XL-v1.0,kandinsky-community_kandinsky-3
4,appendix,13389864,crown.n.06,crown,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,서봉총 금관 금제드리개.jpg,an English coin worth 5 shillings,retrieval,DeepFloyd_IF-I-XL-v1.0
...,...,...,...,...,...,...,...,...,...,...,...
3365,leafs_and_no_leafs_llama,41796839,area.n.03,renal area,['body_part.n.01'],"['abdomen.n.01', 'adnexa.n.01', 'ambulacrum.n....",['https://upload.wikimedia.org/wikipedia/commo...,CT of sclerotic lesions in the skull in renal ...,a part of an animal that has a special functio...,retrieval,stabilityai_stable-diffusion-xl-base-1.0
3366,predict_hypernym_llama,36389327,card_player.n.01,bridge player,['player.n.01'],"['ballplayer.n.01', 'billiard_player.n.01', 'b...",['https://upload.wikimedia.org/wikipedia/commo...,Kevin Collins (bridge player).jpg,someone who plays (or knows how to play) card ...,playgroundai_playground-v2.5-1024px-aesthetic,runwayml_stable-diffusion-v1-5
3367,predict_hypernym_llama,27347584,domestic_partner.n.01,married woman,['person.n.01'],"['abator.n.01', 'abjurer.n.01', 'abomination.n...",['https://upload.wikimedia.org/wikipedia/commo...,The Woman He Married (1922) - 4.jpg,a person (not necessarily a spouse) with whom ...,kandinsky-community_kandinsky-3,stabilityai_sdxl-turbo
3368,predict_hypernym_llama,13967420,body_part.n.01,abdomen,['part.n.03'],"['acicula.n.01', 'base.n.04', 'corner.n.09', '...",['https://upload.wikimedia.org/wikipedia/commo...,Abdomen-periumbilical region.png,any part of an organism such as an organ or ex...,playgroundai_playground-v2.5-1024px-aesthetic,runwayml_stable-diffusion-v1-5
3369,predict_hypernym_llama,78890307,hormone.n.01,gonadotropin,['secretion.n.02'],"['autacoid.n.01', 'ganoin.n.01', 'intestinal_j...",['https://upload.wikimedia.org/wikipedia/commo...,Estrogen provocation test and gonadotropin sur...,the secretion of an endocrine gland that is tr...,runwayml_stable-diffusion-v1-5,playgroundai_playground-v2.5-1024px-aesthetic

In [7]:
df1 = df[df['subset'].str.contains('llama')]

In [12]:
for i, row in df.iterrows():
    if 'llama' in row['subset']:
        print(row['core_lemma'])

numismatics
bee
gold coin
transformation
jewelry
disbeliever
coin
unit of account
bird of prey
gold coin
coin
bird of prey
penny
coin
penny
penny
african country
crown
coin
eagle
penny
coin
money
jewelry
copper-nickel alloy
penny
coin
coin
fraction
reality
coin
penny
mollusk
cuisine
coin
coin
penny
penny
musical quality
color
color
color
color
color
tree
color
color
rose color
color
color
anadromous fish
color
garment
coat
jacket
view
greatcoat
coat
coat
coat
outerwear
coat
fishing net
market
coat
coat
coat
coat
top
ornament
jewel
jewelry
jewelry
jewelry
cutting tool
jewelry
jewelry
treasure
jewelry
point
jewelry
clasp
furnishings
bed
furniture
furniture
case
feast
numismatics
bee
gold coin
transformation
jewelry
disbeliever
coin
unit of account
bird of prey
gold coin
coin
bird of prey
penny
coin
penny
penny
african country
crown
coin
eagle
penny
coin
money
jewelry
copper-nickel alloy
penny
coin
coin
fraction
reality
coin
penny
mollusk
cuisine
coin
coin
penny
penny
musical quality
color
color
color
color
color
tree
color
color
rose color
color
color
anadromous fish
color
garment
coat
jacket
view
greatcoat
coat
coat
coat
outerwear
coat
fishing net
market
coat
coat
coat
coat
top
ornament
jewel
jewelry
jewelry
jewelry
cutting tool
jewelry
jewelry
treasure
jewelry
point
jewelry
clasp
furnishings
bed
furniture
furniture
case
feast
cupboard
furniture
furniture
furniture
fit
stand
light source
furniture
receptacle
furniture
place
part
hotel chain
person
furniture
furniture
unit
furniture
furniture
italian dish
pasta
morsel
pasta
magnoliid dicot
pasta
casserole
pasta
pasta
pasta
pasta
food
grain
macaroni
pasta
pasta
pasta
pasta
pasta
pasta
pasta
pasta
dairy product
blue pigment
cheese
soft cheese
cheese
english cheese
cheese
cheese
cheese
gloucester cheese
cheese
cheese
cheese
cheese
cheese
musical group
limburger cheese
italian cheese
swiss cheese
cheese
cheese
cheese
italian cheese
cheese
cheese
cream
paste
space
chamber
room
room
room
room
room
room
tower
room
meeting room
room
biological science
biological science
room
room
room
room
room
room
room
enclosure
room
control center
tribunal
cubbyhole
room
room
room
dining room
room
passageway
room
gathering
applied science
surface
room
hall
hall
room
room
public building
room
room
repository
room
room
room
hall
room
chamber
cave
room
room
room
architectural style
workshop
kitchen
room
room
room
infirmary
room
room
room
room
bath
room
work
parlor
medical procedure
room
room
bathroom fixture
chamber
meeting room
room
office
room
food
red meat
reptile
cutlet
cured meat
cutting
meat
mollusk
amusement
kashrut
red meat
dried meat
carnivore
sheep
energy-dense food
meat
meat
meat
cured meat
meat
meat
cut of meat
meat
alcohol
wine
red wine
claret
red wine
red wine
appellation of origin
wine
cognac
fortification
kind
wine
city
wine
wine
wine
white wine
wine
wine
red wine
muscovy duck
variety
liqueur
style
wine
vertebrate
saurischian
saurischian
shaker
saurischian
dinosaur
mammal
saurischian
sweet
candy
ball
toughness
caramel
candy
candy
candy
candy
bar
candy
candy
candy
egg
sugar paste
candy
candy
candy
variety
lamiaceous plant
bean
caress
spice
savior
candy
geometric shape
candy
almond paste
herb
candy
bar
bar
flat cake
bar
ball
candy
candy
candy
candy
plum
candy
fungus
delight
potable
beverage
alcoholic beverage
chocolate
stimulant
refrigerator
cut
video game
subject
movie
film
speed
picture
film
dimension
child
bluff
game
game
game
game
card game
straw
rope
play
plaything
game
musical game
game
fight
office
play
spin
label
wink
lower garment
trouser
trousers
cotton fabric
legwear
rope
cotton fabric
trousers
britches
trousers
garment
trouser
cyclist
traditional garment
trousers
loose-fitting trousers
pant
pant
trousers
stringed instrument
guitar
guitar
stringed instrument
guitar
guitar
stringed instrument
centrifugal separator
coal
annotate
pendulum
glass
language
rubber
miner
party
steward
service
buyer
organization
engineering
erotomaniac
entertainer
place
write
hide glue
weaving
incision
reverse
jargon
typescript
irony
eat
yom kippur
radiation
specific dynamic action
horse
adult
garmentmaker
income
coupon bond
boaster
hormone
disbeliever
babble
brush
fairy
house trailer
ritual
pervert
accommodation
pot
armor
drill
calligraphy
sulfate
jazz singing
oldster
worship
skin
admirer
truck
bridge player
pool
barn
abetalipoproteinemia
model
worship
chemical reaction
toy
child molester
religious orientation
dull
foster parent
mechanism
influence
adult
block
sardine
quantity
old person
ornament
disciple
ornament
day
react
stock exchange
apron
antihypertensive
plate armor
sweet
armor plate
tube
orchestrate
potato
association
coal miner
baryon
marine snail
admirer
snail
religious orientation
sweet potato
subatomic particle
sampling
molding
salad dressing
monarch
time period
wanderer
sculpture
demonstration
ester
rosid dicot family
molding
surface
genetic disease
communication
servant
retail store
supporter
sauce
decongestant
hammer
sodium lauryl sulfate
intelligence agency
amazonite
horn
police officer
thalassemia
sport
flap
shout
amnion
darkness
demonstrate
currency
policeman
hormone
armor
object
ball-peen hammer
bonus
morning sickness
disciple
draw
tumor
building
neurochemical
congenital defect
armored vehicle
actor
street
seaman
truck
glass
anguish
abdication
agent
actor
defeat
trailer home
zero-coupon bond
income
march
carnivore
congestion
armor plate
engineering
balloon
motion
punishment
adenomatosis
beat cop
apathy
young cow
assertion
sponge rubber
association
christian
scenery
mechanism
natural phenomenon
burn
block and tackle
count
plaything
molding
exhale
nitrate
police officer
duct
gathering
contract
glass
party
school of art
rectangular parallelepiped
alpine
block
plant fiber
colors
amphotericin b
nitrate of silver
sash
belt
block
quartz
pony
fan
strangler fig
news
scenery
harden
time off
plain
silver
penicillin
nematode
mechanism
plain
antiparticle
maker
gymnosperm
halocarbon
walking
scenery
apprehension
vestment
attorney
electronic warfare
eating
lighter
georgia
battle plan
loyalist
pesticide
anticipation
broadway
pressure gauge
vegetable fiber
outbuilding
bargain
plaything
toy gun
ship's crew
speaker
caste
sermon
narcotic
neuropeptide
surface
cuesta
off-color term
party
subatomic particle
fleshy growth
ragtag
troy ounce
freeze
quarrel
speech
discoordinate
queen
boring drill
admirer
argumentative person
cattle
trader
penicillin G
spirit
celebrity
white
albino
time
relinquishment
dicot family
dye
penal institution
heat
jazz
money
drill
sensibleness
rosid dicot family
eat
rima
phenylephrine
hashish
bevel
oldster
fat
house
armor
accommodation
candlemas
rub
lycopodium
pederast
style
anticipation
computer instruction
sales outlet
shape
pendulum clock
turnip
pervert
lawyer
sensation
senior
write
stiffener
plan
epinephrine
glass
crown
organization
hematuria
pool
possum
legal document
candy
boulder
rubber tree
hajj
miner
nitrogen
vestment
columbus day
norepinephrine
sweat gland
garden snail
headline
bleeding disorder
advice
body armor
region
ape
fluoride
cleft
broadcast
score
resuscitation
plain
pointer
craft
outbuilding
good sense
plain
communication
beta radiation
islam
gland
toy
galley
sweater
aneroid gauge
quarrel
fauvism
board
self-worship
oldster
deck
nylon
questionnaire
friendship
dye
rescission
hit
vinaigrette
magnetism
demonstration
adherent
flap
hemorrhage
jeep
balsamic
inherited disorder
legal document
pillar
liquid mixture
ceremony
mechanism
ridge
cut
sulfate
news
canine
jewish holiday
dicot family
digital computer
magnetism
caravan
speedster
alimony
cook
random sample
gelatin
delicacy
insecticide
engineering science
painting
apothecary weight
sagacity
self-worshipper
birthday party
block of ice
midnight
roundness
phrase
fencing
compensation
horse
agrostis
ablution
obscenity
overemphasize
act
cash flow
impel
teepee
expanse
chew out
statement
hereditary disease
mechanism
profitability
guttering shovel
disc
molding
affirmation
royalist
armored vehicle
glass
apothecary weight
catecholamine
lawyer
prazosin
tumor
ape
expense
exchange
ion
execute
plaything
class
block
refusal
pact
walking
plaything
circuitry
duct
concoct
female reproductive system
quality
sulfonamide
adherent
depression
region
white
lawyer
trap
majority
association
pot
intelligence agency
surface
painting
spraying
write
glass
killing
magnetic field
call-up
christmas
dissociative experience
arming
write
sidereal year
dye
request for
conjunction
buyback
title
sow
ritual
news
chemical reaction
dicot family
sensory receptor site
flogging
hymn
pickup
dressing
heresy
ductus deferens
central intelligence agency
call
cultural enrichment
damage
electromagnetic warfare
larva
vinaigrette
wages
candy
plaything
neuromuscular blocking agent
exceed
author
party
hunting
enthusiast
marquee
radiation
computer
house trailer
theater of war
eructate
sickness
wife
question
face
entertainer
movement
class
anemia
statement
halide
announce
reformed
allowance
fossil fuel
lawyer
wire mesh
quartz
loan
range
armor
skin
sleepwalk
chafe
paper currency
beat
questionnaire
ginkgo
fertilize
truck
new yorker
triglyceride
phenomenon
income
beast of burden
corpse
molding
clubmoss
plan
toy pistol
fovea
fig tree
queen
economic crisis
region
ability
perception
female
macro
body part
tramp
ion
accommodation
belt
inductive reasoning
athlete
engineering
heresy
water spirit
premise
worm
gelatin
trifolium
worm
enthusiast
allegretto
scored
execute
coupon bond
fry
computer
calculator
pillar of islam
jazz
worship
geriatric
walking
mayonnaise
cordialist
time
eat
banyan fig
understanding
change
old person
happiness
marsupial
gonadotropin
chemical reaction
house
self-lover
estimate
truck
abetalipoproteinemia
zoroastrian
walking
experience
hammer
preaching
change
heresy
eavesdropping
musical horn
engineering
trade association
liberal democrat
construction set
armor plate
vinaigrette
factor ii
saint
blue marlin
glass
shovel
instruction
rosid dicot family
play ball
foster father
drill
dysentery
computer
statement
store
earthquake
contract
aikido
bargaining
sun worship
woman
object
laboratory
fat
kitchen servant
natural rubber
certification
opium
plaything
mother
embarrassment
shape
random access memory
worship
experience
heat
stone wall
venesection
servant
geological phenomenon
cost
sweater
process
coil
cotton
jewish festival
mother-in-law
yellow dye
grass
pistol
worm
worship
abdomen
narcotic
stitchwort
nitrate
pilgrimage
muscle relaxant
correlation
acquisition
baptist association
space
artiodactyl
circularity
consumer loan
alignment
controllability
dressing
construction set
antihypertensive
parallelepiped
rag
bleach
fan
chasuble
outweigh
armor plate
leather strip
familial hypercholesterolemia
worship
civic union
grassland
sail
mechanism
tank
mumbo-jumbo
chips
white trash
agreement
almond
freak
atmography
respiration
change of state
batting glove
earth filter
sermon
command
metaphor
operator
fishing trap
blackness
engineering
dasyurid
angularity
vestment
shahid
column
dysentery
toy
braggart
gross sales
start
rag
reassess
embarrassment
plaything
lawyer
condensation
articulated lorry
amitriptyline
chorus
advisory committee
catecholamine
pillar of islam
amino acid
financial condition
control
servant
reversal
glyceride
emblem
party
structure
client
landing ship
refrain
block
jansenism
prolactin
reduce
house
killing
compensate
bulletproof plate
exaggeration
expense
parallelepiped
suicide bomber
saint
goad
able seaman
primate
flap
measure
mechanism
neurotransmitter
secularist
terrorist
net
whist
papilionaceous genus
marmalade
blush
worm
house of correction
prevention
expense
outdo
soil
furnish
photographer
region
arianism
clergyman
dye
ride
swimming pool
ruby
caucasian
pelagic fish
vestment
write
pot
computer
act
reform judaism
club moss
tent
client
prevention
income
fig
time
anemia
female body
blasphemy
worship
electronic countermeasures
supporter
chemical analysis
electronic warfare
archdeacon
layperson
depletion
ship
lighter fluid
locomotion
amount
action
clockwork
point in time
lawyer
knowing
pendulum
candlemas
declare
agreement
negotiate
juggler
fibrillation
candy
house
implement
region
dicot family
bolt
gait
pot
agreement
casserole
iranian
broadcast
grain bin
computer hacker
palm
policeman
christian heresy
marsupial
quantity
meteorology
armor plate
polynomial
homosexual
harm
brush
foster parent
athlete
craft
amity
board
giant water bug
baptist convention
dishonorer
clean
nonsense
armor
hammer
angiotensin
crisp
chemical reaction
street
draw
expense
soil
float glass
experience
believer
labor union
garmentmaker
route
trap
endorser
dressing
rhinitis
shape
net
pickup truck
french food
prayer
sentry
credit
trap
mesh
elementary particle
parliamentary procedure
cancellation
dunnart
familial hypercholesterolemia
accord
man
ball
dopamine
militarization
barracks
tailor
cystic fibrosis
eat
vest
police officer
penicillin
antelope
thief
labor union
year
sight
happen
fishing net
tallow
chemical analysis
crystal
art
craft
double agent
branch
amino acid
adoration
heifer
affect
furlough
carcinoma
miner
sulfonamide
pointer
mother
play
executor
fold
norepinephrine
aquarium
back country
disk
sketch
plate armor
crumple
burst
incision
pickpocket
easel
molding
congenital deafness
paintbrush
coil
drill
seed plant
flow
chemical reaction
carolingian
agreement
speaker
familial hypercholesterolemia
knowledge
implement
income
true bug
reprimand
actor
engineering
retail store
adult
area
write
tank
believe
negotiation
roar
four-armed cross
mechanism
expense
cellulose
personality inventory
clamor
expense
female body
crate
street
engineering
siren
banshee
comedian
battlefield
vinaigrette
exposure
armor plate
good friday
mayonnaise
eat
figure of speech
flying disk
substitution
cultivate
chemical assay
yponomeuta
state
servant
church member
callus
shame
whistle
damage
hammer
moth
accommodation
egotist
plaything
pot
gun
segregate
motion
unmarried person
white person
baseboard
firecracker
wanderer
bring to pass
nonsense
heat
pervert
dioxin
drill
nitrogen
economic condition
armor
flogging
extractor
sore
rework
news
keep a record
cardigan
resin
fasting
negotiation
actor
christian
upthrust
actor
mark
punishment
pendulum
fibrillation
home movie
catholic
saint
shelter
emblem
traveler
cancellation of a flight
movement
glyceride
deaf mutism
domestic
chemical reaction
atrial fibrillation
armor
mechanism
statement
flap
government
genetic disease
blast
last
headline
catherine of aragon
convert
anterior fontanelle
meteorology
street
learning
deposit
flap
amebic dysentery
flap
afterdeck
allergic rhinitis
reaction
pleural effusion
tire
ship
pilgrimage
party
curare
alcove
zealot
caryophyllaceae
armor plate
jew
emphasize
resin
hammer
animal
pistol
sensory modality
inherited disorder
utterance
craft
surpass
baster
amnion
walk
region
toy
happiness
declare
sulfonamide
nonsense
happiness
gobble
molding
tool shed
job
magnetic coil
servant
acquisition
association
change
salt
disorder
heresy
graft
utterance
roundness
tank
beauty parlor
martial art
deck
worship
antihistamine
nonsense
bow
cosmic event
alizarin
association
club moss
easter
depreciation
partner
retinal area
dye
actor
kitchen
dicot family
sickness
prevention
ficus
arming
actress
backer
glass
karakalpak
antiprotozoal
supernatural being
mercantile establishment
worship
sex
run
succulent
rescue breathing
tank
hemp
chemical reaction
pistol
observation
liquid nitrogen
tent
catecholamine
aristocracy
ballplayer
aeronautical engineering
discriminate
separate
turk
absolute monarch
rhinitis
bark
addition
duct
petty officer
renal area
bridge player
married woman
abdomen
gonadotropin