In [40]:
import pandas as pd
import random
import os
import nltk
nltk.download('wordnet')
from nltk.corpus import wordnet as wn
from tqdm import tqdm

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [41]:
df = pd.read_csv('main.tsv', sep='\t')

In [42]:
models_list = os.listdir('/home/data/v.moskvoretskii/taxo_demo_images/images/')

In [43]:
df['core_synset'][0]

'coin.n.01'

In [44]:
df['definition'] = [wn.synset(df['core_synset'][i]).definition() for i in tqdm(range(len(df)))]

100%|██████████| 3370/3370 [00:00<00:00, 99129.00it/s]

In [45]:
df

,subset,wordnet_id,core_synset,core_lemma,hypernym_synsets,cohyponym_synsets,wikimedia_images,image_filename,definition
0,appendix,13388245,coin.n.01,coin,['coinage.n.01'],['coin.n.01'],['https://upload.wikimedia.org/wikipedia/commo...,"India, Kushan, Vasudeva II, 3rd century - Coin...",a flat metal piece (usually a disc) used as money
1,appendix,13389105,bawbee.n.01,bawbee,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,Mary bawbee 1542 127326.jpg,an old Scottish coin of little value
2,appendix,13389194,bezant.n.01,bezant,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,Crusader coins of the Kingdom of Jerusalem.jpg,a gold coin of the Byzantine Empire; widely ci...
3,appendix,13388111,change.n.08,change,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,Change in Average Temperature With Fahrenheit.svg,coins of small denomination regarded collectively
4,appendix,13389864,crown.n.06,crown,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,서봉총 금관 금제드리개.jpg,an English coin worth 5 shillings
...,...,...,...,...,...,...,...,...,...
3365,leafs_and_no_leafs_llama,41796839,area.n.03,renal area,['body_part.n.01'],"['abdomen.n.01', 'adnexa.n.01', 'ambulacrum.n....",['https://upload.wikimedia.org/wikipedia/commo...,CT of sclerotic lesions in the skull in renal ...,a part of an animal that has a special functio...
3366,predict_hypernym_llama,36389327,card_player.n.01,bridge player,['player.n.01'],"['ballplayer.n.01', 'billiard_player.n.01', 'b...",['https://upload.wikimedia.org/wikipedia/commo...,Kevin Collins (bridge player).jpg,someone who plays (or knows how to play) card ...
3367,predict_hypernym_llama,27347584,domestic_partner.n.01,married woman,['person.n.01'],"['abator.n.01', 'abjurer.n.01', 'abomination.n...",['https://upload.wikimedia.org/wikipedia/commo...,The Woman He Married (1922) - 4.jpg,a person (not necessarily a spouse) with whom ...
3368,predict_hypernym_llama,13967420,body_part.n.01,abdomen,['part.n.03'],"['acicula.n.01', 'base.n.04', 'corner.n.09', '...",['https://upload.wikimedia.org/wikipedia/commo...,Abdomen-periumbilical region.png,any part of an organism such as an organ or ex...
3369,predict_hypernym_llama,78890307,hormone.n.01,gonadotropin,['secretion.n.02'],"['autacoid.n.01', 'ganoin.n.01', 'intestinal_j...",['https://upload.wikimedia.org/wikipedia/commo...,Estrogen provocation test and gonadotropin sur...,the secretion of an endocrine gland that is tr...

In [46]:

# target_size = 4 * 1000
# rows_needed = target_size - len(df)
# additional_rows = df.sample(n=rows_needed, replace=True)
# expanded_df = pd.concat([df, additional_rows], ignore_index=True)

#models_list = ['SD3', 'SDXL', 'SDXL_Turbo', 'Kandinsky', 'PixArt_Sigma', 'Playground', 'IF', 'Openjourney', 'Hunyuan-DiT', 'SD_V1.5', 'Retrieved']

def sample_model_pair(models_list):
    return random.sample(models_list, 2)

# Adding the sampled pairs to the dataframe
df[['model_a', 'model_b']] = df.apply(lambda row: pd.Series(sample_model_pair(models_list)), axis=1)

In [47]:
df

,subset,wordnet_id,core_synset,core_lemma,hypernym_synsets,cohyponym_synsets,wikimedia_images,image_filename,definition,model_a,model_b
0,appendix,13388245,coin.n.01,coin,['coinage.n.01'],['coin.n.01'],['https://upload.wikimedia.org/wikipedia/commo...,"India, Kushan, Vasudeva II, 3rd century - Coin...",a flat metal piece (usually a disc) used as money,playgroundai_playground-v2.5-1024px-aesthetic,retrieval
1,appendix,13389105,bawbee.n.01,bawbee,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,Mary bawbee 1542 127326.jpg,an old Scottish coin of little value,runwayml_stable-diffusion-v1-5,stabilityai_stable-diffusion-xl-base-1.0
2,appendix,13389194,bezant.n.01,bezant,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,Crusader coins of the Kingdom of Jerusalem.jpg,a gold coin of the Byzantine Empire; widely ci...,PixArt-alpha_PixArt-Sigma-XL-2-512-MS,runwayml_stable-diffusion-v1-5
3,appendix,13388111,change.n.08,change,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,Change in Average Temperature With Fahrenheit.svg,coins of small denomination regarded collectively,DeepFloyd_IF-I-XL-v1.0,kandinsky-community_kandinsky-3
4,appendix,13389864,crown.n.06,crown,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,서봉총 금관 금제드리개.jpg,an English coin worth 5 shillings,retrieval,DeepFloyd_IF-I-XL-v1.0
...,...,...,...,...,...,...,...,...,...,...,...
3365,leafs_and_no_leafs_llama,41796839,area.n.03,renal area,['body_part.n.01'],"['abdomen.n.01', 'adnexa.n.01', 'ambulacrum.n....",['https://upload.wikimedia.org/wikipedia/commo...,CT of sclerotic lesions in the skull in renal ...,a part of an animal that has a special functio...,retrieval,stabilityai_stable-diffusion-xl-base-1.0
3366,predict_hypernym_llama,36389327,card_player.n.01,bridge player,['player.n.01'],"['ballplayer.n.01', 'billiard_player.n.01', 'b...",['https://upload.wikimedia.org/wikipedia/commo...,Kevin Collins (bridge player).jpg,someone who plays (or knows how to play) card ...,playgroundai_playground-v2.5-1024px-aesthetic,runwayml_stable-diffusion-v1-5
3367,predict_hypernym_llama,27347584,domestic_partner.n.01,married woman,['person.n.01'],"['abator.n.01', 'abjurer.n.01', 'abomination.n...",['https://upload.wikimedia.org/wikipedia/commo...,The Woman He Married (1922) - 4.jpg,a person (not necessarily a spouse) with whom ...,kandinsky-community_kandinsky-3,stabilityai_sdxl-turbo
3368,predict_hypernym_llama,13967420,body_part.n.01,abdomen,['part.n.03'],"['acicula.n.01', 'base.n.04', 'corner.n.09', '...",['https://upload.wikimedia.org/wikipedia/commo...,Abdomen-periumbilical region.png,any part of an organism such as an organ or ex...,playgroundai_playground-v2.5-1024px-aesthetic,runwayml_stable-diffusion-v1-5
3369,predict_hypernym_llama,78890307,hormone.n.01,gonadotropin,['secretion.n.02'],"['autacoid.n.01', 'ganoin.n.01', 'intestinal_j...",['https://upload.wikimedia.org/wikipedia/commo...,Estrogen provocation test and gonadotropin sur...,the secretion of an endocrine gland that is tr...,runwayml_stable-diffusion-v1-5,playgroundai_playground-v2.5-1024px-aesthetic

In [48]:
df.to_csv('main.csv', index=0)

In [49]:
n = len(df) // 4

# Splitting into four parts
df1 = df.iloc[:n]
df2 = df.iloc[n:2*n]
df3 = df.iloc[2*n:3*n]
df4 = df.iloc[3*n:]

In [50]:
len(df1), len(df4)

(842, 844)

In [51]:
df1.to_csv('alina.csv', index=0)
df2.to_csv('kate.csv', index=0)
df3.to_csv('vitya.csv', index=0)
df4.to_csv('ira.csv', index=0)