In [32]:
import pandas as pd
import random
import os
import nltk
nltk.download('wordnet')
from nltk.corpus import wordnet as wn
from tqdm import tqdm

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [17]:
df = pd.read_csv('main.tsv', sep='\t')

In [5]:
models_list = os.listdir('/home/data/v.moskvoretskii/taxo_demo_images/images/')

In [24]:
df['core_synset'][0]

'coin.n.01'

In [33]:
df['definition'] = [wn.synset(df['core_synset'][i]).definition() for i in tqdm(range(len(df)))]

100%|██████████| 3370/3370 [00:00<00:00, 20595.30it/s]

In [34]:
df

,subset,wordnet_id,core_synset,core_lemma,hypernym_synsets,cohyponym_synsets,wikimedia_images,image_filename,definition
0,appendix,13388245,coin.n.01,coin,['coinage.n.01'],['coin.n.01'],['https://upload.wikimedia.org/wikipedia/commo...,"India, Kushan, Vasudeva II, 3rd century - Coin...",a flat metal piece (usually a disc) used as money
1,appendix,13389105,bawbee.n.01,bawbee,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,Mary bawbee 1542 127326.jpg,an old Scottish coin of little value
2,appendix,13389194,bezant.n.01,bezant,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,Crusader coins of the Kingdom of Jerusalem.jpg,a gold coin of the Byzantine Empire; widely ci...
3,appendix,13388111,change.n.08,change,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,Change in Average Temperature With Fahrenheit.svg,coins of small denomination regarded collectively
4,appendix,13389864,crown.n.06,crown,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,서봉총 금관 금제드리개.jpg,an English coin worth 5 shillings
...,...,...,...,...,...,...,...,...,...
3365,leafs_and_no_leafs_llama,41796839,area.n.03,renal area,['body_part.n.01'],"['abdomen.n.01', 'adnexa.n.01', 'ambulacrum.n....",['https://upload.wikimedia.org/wikipedia/commo...,CT of sclerotic lesions in the skull in renal ...,a part of an animal that has a special functio...
3366,predict_hypernym_llama,36389327,card_player.n.01,bridge player,['player.n.01'],"['ballplayer.n.01', 'billiard_player.n.01', 'b...",['https://upload.wikimedia.org/wikipedia/commo...,Kevin Collins (bridge player).jpg,someone who plays (or knows how to play) card ...
3367,predict_hypernym_llama,27347584,domestic_partner.n.01,married woman,['person.n.01'],"['abator.n.01', 'abjurer.n.01', 'abomination.n...",['https://upload.wikimedia.org/wikipedia/commo...,The Woman He Married (1922) - 4.jpg,a person (not necessarily a spouse) with whom ...
3368,predict_hypernym_llama,13967420,body_part.n.01,abdomen,['part.n.03'],"['acicula.n.01', 'base.n.04', 'corner.n.09', '...",['https://upload.wikimedia.org/wikipedia/commo...,Abdomen-periumbilical region.png,any part of an organism such as an organ or ex...
3369,predict_hypernym_llama,78890307,hormone.n.01,gonadotropin,['secretion.n.02'],"['autacoid.n.01', 'ganoin.n.01', 'intestinal_j...",['https://upload.wikimedia.org/wikipedia/commo...,Estrogen provocation test and gonadotropin sur...,the secretion of an endocrine gland that is tr...

In [35]:

# target_size = 4 * 1000
# rows_needed = target_size - len(df)
# additional_rows = df.sample(n=rows_needed, replace=True)
# expanded_df = pd.concat([df, additional_rows], ignore_index=True)

#models_list = ['SD3', 'SDXL', 'SDXL_Turbo', 'Kandinsky', 'PixArt_Sigma', 'Playground', 'IF', 'Openjourney', 'Hunyuan-DiT', 'SD_V1.5', 'Retrieved']

def sample_model_pair(models_list):
    return random.sample(models_list, 2)

# Adding the sampled pairs to the dataframe
df[['model_a', 'model_b']] = df.apply(lambda row: pd.Series(sample_model_pair(models_list)), axis=1)

In [36]:
df

,subset,wordnet_id,core_synset,core_lemma,hypernym_synsets,cohyponym_synsets,wikimedia_images,image_filename,definition,model_a,model_b
0,appendix,13388245,coin.n.01,coin,['coinage.n.01'],['coin.n.01'],['https://upload.wikimedia.org/wikipedia/commo...,"India, Kushan, Vasudeva II, 3rd century - Coin...",a flat metal piece (usually a disc) used as money,prompthero_openjourney,Tencent-Hunyuan_HunyuanDiT-v1.2-Diffusers
1,appendix,13389105,bawbee.n.01,bawbee,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,Mary bawbee 1542 127326.jpg,an old Scottish coin of little value,stabilityai_stable-diffusion-xl-base-1.0,retrieval
2,appendix,13389194,bezant.n.01,bezant,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,Crusader coins of the Kingdom of Jerusalem.jpg,a gold coin of the Byzantine Empire; widely ci...,Tencent-Hunyuan_HunyuanDiT-v1.2-Diffusers,stabilityai_stable-diffusion-3-medium-diffusers
3,appendix,13388111,change.n.08,change,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,Change in Average Temperature With Fahrenheit.svg,coins of small denomination regarded collectively,Tencent-Hunyuan_HunyuanDiT-v1.2-Diffusers,stabilityai_sdxl-turbo
4,appendix,13389864,crown.n.06,crown,['coin.n.01'],"['bawbee.n.01', 'bezant.n.01', 'change.n.08', ...",['https://upload.wikimedia.org/wikipedia/commo...,서봉총 금관 금제드리개.jpg,an English coin worth 5 shillings,playgroundai_playground-v2.5-1024px-aesthetic,DeepFloyd_IF-I-XL-v1.0
...,...,...,...,...,...,...,...,...,...,...,...
3365,leafs_and_no_leafs_llama,41796839,area.n.03,renal area,['body_part.n.01'],"['abdomen.n.01', 'adnexa.n.01', 'ambulacrum.n....",['https://upload.wikimedia.org/wikipedia/commo...,CT of sclerotic lesions in the skull in renal ...,a part of an animal that has a special functio...,PixArt-alpha_PixArt-Sigma-XL-2-512-MS,DeepFloyd_IF-I-XL-v1.0
3366,predict_hypernym_llama,36389327,card_player.n.01,bridge player,['player.n.01'],"['ballplayer.n.01', 'billiard_player.n.01', 'b...",['https://upload.wikimedia.org/wikipedia/commo...,Kevin Collins (bridge player).jpg,someone who plays (or knows how to play) card ...,PixArt-alpha_PixArt-Sigma-XL-2-512-MS,DeepFloyd_IF-I-XL-v1.0
3367,predict_hypernym_llama,27347584,domestic_partner.n.01,married woman,['person.n.01'],"['abator.n.01', 'abjurer.n.01', 'abomination.n...",['https://upload.wikimedia.org/wikipedia/commo...,The Woman He Married (1922) - 4.jpg,a person (not necessarily a spouse) with whom ...,Tencent-Hunyuan_HunyuanDiT-v1.2-Diffusers,retrieval
3368,predict_hypernym_llama,13967420,body_part.n.01,abdomen,['part.n.03'],"['acicula.n.01', 'base.n.04', 'corner.n.09', '...",['https://upload.wikimedia.org/wikipedia/commo...,Abdomen-periumbilical region.png,any part of an organism such as an organ or ex...,stabilityai_stable-diffusion-xl-base-1.0,kandinsky-community_kandinsky-3
3369,predict_hypernym_llama,78890307,hormone.n.01,gonadotropin,['secretion.n.02'],"['autacoid.n.01', 'ganoin.n.01', 'intestinal_j...",['https://upload.wikimedia.org/wikipedia/commo...,Estrogen provocation test and gonadotropin sur...,the secretion of an endocrine gland that is tr...,PixArt-alpha_PixArt-Sigma-XL-2-512-MS,playgroundai_playground-v2.5-1024px-aesthetic

In [37]:
sample = df.sample(100)

In [38]:
sample.to_csv('annotator_agreement.csv', index=0)

In [11]:
ad = pd.read_csv('annotator_agreement.csv')

In [12]:
ad

,subset,wordnet_id,core_synset,core_lemma,hypernym_synsets,cohyponym_synsets,wikimedia_images,image_filename,model_a,model_b
0,appendix,7896560,jug_wine.n.01,jug_wine,['wine.n.01'],"['altar_wine.n.01', 'blush_wine.n.01', 'bordea...",['https://upload.wikimedia.org/wikipedia/commo...,Jug wine.jpg,kandinsky-community_kandinsky-3,Tencent-Hunyuan_HunyuanDiT-v1.2-Diffusers
1,appendix_llama,46972907,pie.n.01,candy,['pastry.n.02'],"['baklava.n.01', 'dowdy.n.02', 'frangipane.n.0...",['https://upload.wikimedia.org/wikipedia/commo...,Ambigram Candy icon - pink animated.gif,playgroundai_playground-v2.5-1024px-aesthetic,runwayml_stable-diffusion-v1-5
2,predict_hypernym_llama,30823361,advocate.n.01,admirer,['person.n.01'],"['abator.n.01', 'abjurer.n.01', 'abomination.n...",['https://upload.wikimedia.org/wikipedia/commo...,The Admirer by Eugenio Zampighi.jpg,retrieval,stabilityai_stable-diffusion-3-medium-diffusers
3,appendix,2676566,acoustic_guitar.n.01,acoustic_guitar,['guitar.n.01'],"['acoustic_guitar.n.01', 'bass_guitar.n.01', '...",['https://upload.wikimedia.org/wikipedia/commo...,Man playing an acoustic brazilian guitar (Viol...,DeepFloyd_IF-I-XL-v1.0,playgroundai_playground-v2.5-1024px-aesthetic
4,appendix_llama,14942245,beverage.n.01,meat,"['food.n.01', 'liquid.n.01']","['chyme.n.01', 'comestible.n.01', 'comfort_foo...",['https://upload.wikimedia.org/wikipedia/commo...,Mercado Municipal (São Paulo) 07.jpg,playgroundai_playground-v2.5-1024px-aesthetic,kandinsky-community_kandinsky-3
...,...,...,...,...,...,...,...,...,...,...
95,appendix_llama,38161491,coat.n.01,coat,['overgarment.n.01'],"['aba.n.01', 'cloak.n.02', 'izar.n.01', 'snows...",['https://upload.wikimedia.org/wikipedia/commo...,Coat of arms of Seychelles.svg,kandinsky-community_kandinsky-3,stabilityai_sdxl-turbo
96,leafs_and_no_leafs,762889,horse-trade.v.01,horse-trade,['negociate.v.05'],"['parley.v.01', 'renegociate.v.01', 'treat.v.07']",['https://upload.wikimedia.org/wikipedia/commo...,"Chatsworth Horse Trials, trade stands - geogra...",stabilityai_stable-diffusion-3-medium-diffusers,PixArt-alpha_PixArt-Sigma-XL-2-512-MS
97,predict_hypernym_llama,74999178,represent.v.09,write,['re-create.v.01'],"['act.v.03', 'fictionalize.v.01', 'forge.v.02'...",['https://upload.wikimedia.org/wikipedia/commo...,Fountain pen writing (literacy).jpg,playgroundai_playground-v2.5-1024px-aesthetic,kandinsky-community_kandinsky-3
98,appendix,4025130,puppet.n.03,puppet,['doll.n.01'],"['golliwog.n.01', 'kachina.n.03', 'paper_doll....",['https://upload.wikimedia.org/wikipedia/commo...,PUPPET.jpg,PixArt-alpha_PixArt-Sigma-XL-2-512-MS,Tencent-Hunyuan_HunyuanDiT-v1.2-Diffusers
99,predict_hypernym_llama,76096310,gastropod.n.01,marine snail,['mollusk.n.01'],"['bivalve.n.01', 'cephalopod.n.01', 'chiton.n....",['https://upload.wikimedia.org/wikipedia/commo...,Scheme snail anatomy-numbers.svg,DeepFloyd_IF-I-XL-v1.0,PixArt-alpha_PixArt-Sigma-XL-2-512-MS

In [39]:
df.to_csv('main.csv', index=0)